#ifndef __LINK_TENSORRT_H__
#define __LINK_TENSORRT_H__

#pragma comment(lib, "nvinfer") 
#pragma comment(lib, "nvinfer_plugin") 
#pragma comment(lib, "nvonnxparser") 
#pragma comment(lib, "nvparsers") 

// C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64
#pragma comment(lib, "cublas.lib")
#pragma comment(lib, "cublasLt.lib")
#pragma comment(lib, "cuda.lib")
#pragma comment(lib, "cudadevrt.lib")
#pragma comment(lib, "cudart.lib")
#pragma comment(lib, "cudart_static.lib")
#pragma comment(lib, "cudnn.lib")
#pragma comment(lib, "cufft.lib")
#pragma comment(lib, "cufftw.lib")
#pragma comment(lib, "curand.lib")
#pragma comment(lib, "cusolver.lib")
#pragma comment(lib, "cusparse.lib")
#pragma comment(lib, "nppc.lib")
#pragma comment(lib, "nppial.lib")
#pragma comment(lib, "nppicc.lib")
#pragma comment(lib, "nppicom.lib")
#pragma comment(lib, "nppidei.lib")
#pragma comment(lib, "nppif.lib")
#pragma comment(lib, "nppig.lib")
#pragma comment(lib, "nppim.lib")
#pragma comment(lib, "nppist.lib")
#pragma comment(lib, "nppisu.lib")
#pragma comment(lib, "nppitc.lib")
#pragma comment(lib, "npps.lib")
#pragma comment(lib, "nvblas.lib")
#pragma comment(lib, "nvgraph.lib")
#pragma comment(lib, "nvml.lib")
#pragma comment(lib, "nvrtc.lib")
#pragma comment(lib, "OpenCL.lib")

#endif /* __LINK_TENSORRT_H__ */